/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasrentalmobil;



import java.sql.SQLException;
import java.util.Random;
import java.sql.Connection;
import conn.Data_Transaksi;
import conn.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */


public class TransaksiRental extends javax.swing.JFrame {
    
    Connection conn = koneksi.getKoneksi();
    ResultSet rs = null;
    PreparedStatement pst = null;
    
  private void ViewData(){
    Data_Transaksi dt = new Data_Transaksi();
    try{
        jTable1.setModel(DbUtils.resultSetToTableModel(dt.UpdatedatamobilT()));
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }
  
  
    /**
     * Creates new form TransaksiRental
     */
    public TransaksiRental() {
        initComponents();
    }
    
     private static String generateRandomCode() {
      int length = 4; // Ubah panjang kode sesuai kebutuhan
        StringBuilder sb = new StringBuilder();

        // Karakter yang mungkin ada dalam kode (hanya angka)
        String numericCharacters = "0123456789";

        Random random = new Random();

        // Generate kode acak dengan panjang tertentu
        for (int i = 0; i < length; i++) {
            int index = random.nextInt(numericCharacters.length());
            char randomChar = numericCharacters.charAt(index);
            sb.append(randomChar);
        }

        // Tambahkan akhiran berdasarkan menit dan detik
        long currentTimeMillis = System.currentTimeMillis();
        long seconds = (currentTimeMillis / 1000) % 60;
        long minutes = ((currentTimeMillis / 1000) / 60) % 60;

        sb.append(String.format("%02d%02d", minutes, seconds));

        return sb.toString();
    
}
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nmPenyewa = new javax.swing.JTextField();
        nmMobil = new javax.swing.JTextField();
        KTP = new javax.swing.JTextField();
        MBL = new javax.swing.JTextField();
        noTransaksi = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tTotal = new javax.swing.JTextField();
        hargaRental = new javax.swing.JTextField();
        lamaRental = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        idMobil = new javax.swing.JComboBox<>();
        noKtp = new javax.swing.JComboBox<>();
        Hitung = new javax.swing.JButton();

        nmPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmPenyewaActionPerformed(evt);
            }
        });

        noTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTransaksiActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PROSES TRANSAKSI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PASTIKAN INPUT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DENGAN BENAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/th (3).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, 40));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("TRANSAKSI RENTAL MOBIL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Harga Rental");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Lama Rental");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Total Pembayaran");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        tTotal.setEditable(false);
        jPanel2.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 120, -1));

        hargaRental.setEditable(false);
        jPanel2.add(hargaRental, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, -1));

        lamaRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaRentalActionPerformed(evt);
            }
        });
        jPanel2.add(lamaRental, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 90, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 80, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 90, 40));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "no_transaksi", "no_ktp", "id_mobil", "lama_sewa", "harga", "total", "nama_penyewa", "nama_mobil"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 770, 210));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("No Ktp");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Id Mobil");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Cetak");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 80, 40));

        idMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Id Mobil-" }));
        idMobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idMobilItemStateChanged(evt);
            }
        });
        jPanel2.add(idMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 130, -1));

        noKtp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih No Ktp-" }));
        noKtp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noKtpItemStateChanged(evt);
            }
        });
        jPanel2.add(noKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel2.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lamaRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaRentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaRentalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String randomCode = generateRandomCode();
            String result = "RNTL" + randomCode;
        
            Data_Transaksi dt = new Data_Transaksi();
             dt.no_transaksi = result;
             dt.no_ktp = noKtp.getSelectedItem().toString();
             dt.id_mobil = idMobil.getSelectedItem().toString();
             dt.lama_sewa = lamaRental.getText();
             dt.harga = hargaRental.getText();
             dt.total = tTotal.getText();
             
              if(
              noKtp.getSelectedIndex()==0 ||
              idMobil.getSelectedIndex()==0 
                      ){
                  JOptionPane.showMessageDialog(null, "Lengkapi Data Dulu");
              }else{
                  try {
              dt.simpan();
              JOptionPane.showMessageDialog(null, "Data Berhasil di tambah");
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }ViewData();
              }
              
          
          noTransaksi.setText("");
              noKtp.setSelectedIndex(0);
              idMobil.setSelectedIndex(0);
              hargaRental.setText("");
              lamaRental.setText("");
              tTotal.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
         
         noTransaksi.setText(tb.getValueAt(jTable1.getSelectedRow(), 0).toString());
         noKtp.setSelectedItem(tb.getValueAt(jTable1.getSelectedRow(), 1).toString());
         idMobil.setSelectedItem(tb.getValueAt(jTable1.getSelectedRow(), 2).toString());
         lamaRental.setText(tb.getValueAt(jTable1.getSelectedRow(), 3).toString());
         hargaRental.setText(tb.getValueAt(jTable1.getSelectedRow(), 4).toString());
         tTotal.setText(tb.getValueAt(jTable1.getSelectedRow(), 5).toString());
         
            // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          Data_Transaksi dt = new Data_Transaksi();
             dt.no_transaksi = noTransaksi.getText();
             dt.no_ktp = KTP.getText();
             dt.id_mobil = MBL.getText();
             dt.lama_sewa = lamaRental.getText();
             dt.harga = hargaRental.getText();
             dt.total = tTotal.getText();
             
              int selected = jTable1.getSelectedRow();
        if(selected>=0){
          try {
             PreparedStatement ps;
        String executeQuery = "update transaksi set no_ktp=?, id_mobil=?, lama_sewa=?, harga=?, total=? where no_transaksi=?";
                ps = conn.prepareStatement(executeQuery);
               ps.setString (1, dt.no_ktp);
                ps.setString (2, dt.id_mobil);
                 ps.setString (3, dt.lama_sewa);
                ps.setString (4, dt.harga);
                 ps.setString (5, dt.total);
                 ps.setString (6, dt.no_transaksi);
                 ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "DataTransaksi Diubah");
        } catch (SQLException e) {
            System.err.println(e);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data transaksi yang ingin diubah");
        }
        noTransaksi.setText("");
               noKtp.setSelectedIndex(0);
              idMobil.setSelectedIndex(0);;
              hargaRental.setText("");
              lamaRental.setText("");
              tTotal.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              noTransaksi.setText("");
               noKtp.setSelectedIndex(0);
              idMobil.setSelectedIndex(0);;
              hargaRental.setText("");
              lamaRental.setText("");
              tTotal.setText("");
              
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

         int selected = jTable1.getSelectedRow();
        if(selected>=0){
          try {
              String ObjButtons[]={"Yes","No"};
        int PromptResult = JOptionPane.showOptionDialog(null, "Yakin Ingin Menghapus ?", "Massage", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
              if(PromptResult==0){
            Data_Transaksi dt = new Data_Transaksi();
            dt.no_transaksi = noTransaksi.getText();
                dt.hapus();
                JOptionPane.showMessageDialog(null, "Hapus");
                ViewData();
        }        
        } catch (SQLException e) {
            System.err.println(e);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data transaksi yang ingin diubah");
        }
         noTransaksi.setText("");
               noKtp.setSelectedIndex(0);
              idMobil.setSelectedIndex(0);;
              hargaRental.setText("");
              lamaRental.setText("");
              tTotal.setText("");
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      try {
            HashMap<String, Object> parameter = new HashMap();            
            JasperPrint jp = JasperFillManager.fillReport("src\\uasrentalmobil\\TransaksiReport.jasper", parameter, conn);
            JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        } catch(Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new RentalMenu().show();
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        DefaultTableModel tabel = (DefaultTableModel)jTable1.getModel();
        tabel.setRowCount(0);
        ViewData();
       noKtp.removeAllItems();
       noKtp.addItem("-Pilih No Ktp-");
       idMobil.removeAllItems();
       idMobil.addItem("-Pilih Id Mobil-");
        conn = koneksi.getKoneksi();
        
        Statement st;
       try {  
        st = conn.createStatement();
        ResultSet rs= st.executeQuery("select * from data_penyewa");
            while (rs.next()) {  
             noKtp.addItem(rs.getString("no_ktp"));  
             }
        } catch (Exception ex) {  
        System.err.println("Error : "+ex);
        }
        try {  
        st = conn.createStatement();
        ResultSet rs= st.executeQuery("select * from data_mobil");
            while (rs.next()) {  
             idMobil.addItem(rs.getString("id_mobil"));  
             }
        } catch (Exception ex) {  
        System.err.println("Error : "+ex);
        }


    }//GEN-LAST:event_formWindowActivated

    private void nmPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmPenyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmPenyewaActionPerformed

    private void noTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTransaksiActionPerformed

    private void noKtpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noKtpItemStateChanged
               String ktp =(String) noKtp.getSelectedItem();
               conn = koneksi.getKoneksi();
               PreparedStatement ps;
               ResultSet rs;
        try{
            String qry = "select * from data_penyewa where no_ktp = ?";
            ps = conn.prepareStatement(qry);
            ps.setString(1, ktp);
            rs = ps.executeQuery();
            if(rs.next()){
                String nama = rs.getString("nama_penyewa");
                nmPenyewa.setText(nama);
                String kk = rs.getString("no_ktp");
                KTP.setText(kk);
            }
        }catch(SQLException ex){
            System.err.println("error :" +ex);
        }
    }//GEN-LAST:event_noKtpItemStateChanged

    private void idMobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idMobilItemStateChanged
        String mobil =(String) idMobil.getSelectedItem();
               conn = koneksi.getKoneksi();
               PreparedStatement ps;
               ResultSet rs;
        try{
            String qry = "select * from data_mobil where id_mobil = ?";
            ps = conn.prepareStatement(qry);
            ps.setString(1, mobil);
            rs = ps.executeQuery();
            if(rs.next()){
                String nama = rs.getString("nama_mobil");
                nmMobil.setText(nama);
                String mob = rs.getString("id_mobil");
                MBL.setText(mob);
                 String harga = rs.getString("harga_mobil");
                hargaRental.setText(harga);
            }
        }catch(SQLException ex){
            System.err.println("error :" +ex);
        }
    }//GEN-LAST:event_idMobilItemStateChanged

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
          String hrg = hargaRental.getText();
        if(hrg.isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukkan Id Mobil");
        }else if(lamaRental.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Masukkan Lama Sewa");
    }else{
              int harga = Integer.parseInt(hargaRental.getText());
              int lama = Integer.parseInt(lamaRental.getText());
             int hasil = harga * lama;
             String total = Integer.toString(hasil);
             tTotal.setText(total);
        }
    }//GEN-LAST:event_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField KTP;
    private javax.swing.JTextField MBL;
    private javax.swing.JTextField hargaRental;
    private javax.swing.JComboBox<String> idMobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lamaRental;
    private javax.swing.JTextField nmMobil;
    private javax.swing.JTextField nmPenyewa;
    private javax.swing.JComboBox<String> noKtp;
    private javax.swing.JTextField noTransaksi;
    private javax.swing.JTextField tTotal;
    // End of variables declaration//GEN-END:variables
}
